### PR TITLE
Aesthetic improvements, additional documentation

### PR DESCRIPTION
**Pull request by x94carbone**
Mostly some general aesthetic improvements. Mainly, this is so @ziatdinovmax can see my general style and suggest any improvements. No additional features have really been added.

- [x] Passes all local tests

### CODE REVIEW

**Review by ziatdinovmax — COMMENTED** [review]
Thanks, Matthew. This looks very nice. 

A few comments/questions:
- Did you have a chance to build documentation pages after changing docstrings to confirm that they are read correctly by sphinx?
- I think we don't need to repeat annotation types in the docstrings since the sphinx_autodoc_typehints extension will take care of it when building the documentation.
- For ```import torch.tensor as tt``` I followed the [Theano convention](https://www.google.com/search?q=import+theano.tensor+as+tt&rlz=1CAKDZI_enUS911&sxsrf=ALeKk03vV3OkMS42RuBRP111xu-PMJIscQ%3A1619563533234&ei=DZSIYJXkDY2WtQXV_Y-gBQ&oq=theano.tensor+tt&gs_lcp=Cgdnd3Mtd2l6EAMYADIGCAAQFhAeOgUIABCwAzoJCAAQsAMQBxAeOgQIABAeUPQcWIYgYL8raAFwAHgAgAGWAogBygSSAQUyLjEuMZgBAKABAaoBB2d3cy13aXrIAQrAAQE&sclient=gws-wiz) (Theano is a DL library which was quite popular back in the day). Forgetting to convert something to torch.tensor is one of the most common sources of bugs, and having to type torch.tensor all the time just drives me crazy.

**Comment by x94carbone** [comment]
Sure no problem! 

> Did you have a chance to build documentation pages after changing docstrings to confirm that they are read correctly by sphinx?
No this was an oversight on my end. What's your process for building the docs locally? Is it as simple as running `make` in the `docs` directory?

> I think we don't need to repeat annotation types in the docstrings since the sphinx_autodoc_typehints extension will take care of it when building the documentation.
Ah that's a nice feature. Ok sounds good. Once I am able to build and see what the docs look like I can make the appropriate adjustments if necessary.

> For import torch.tensor as tt I followed the Theano convention (Theano is a DL library which was quite popular back in the day). Forgetting to convert something to torch.tensor is one of the most common sources of bugs, and having to type torch.tensor all the time just drives me crazy.
Sure no problem, I didn't realize it was a standard convention. Would you like me to revert those changes for consistency?

**Comment by x94carbone** [comment]
Well I figured out how to build it. Not too bad.

image

That said, doesn't look like this built properly!

image

It also did not properly use the `__init__` parameters. Oh well. I'll rewrite it, rebuild, check and push when I'm done.

By the way, should I be worried about all the warnings that are thrown during `make html`? I honestly do not have so much experience using Sphinx, thanks!

**Comment by x94carbone** [comment]
So the only complaint I'd have is that it doesn't seem the Sphinx build properly formats the `Attributes` header. You can see below that when I do not include the type in the docstring, that everything is consistent with your style. I did, however, include the types in the attributes, and you can see that the style is different.

image

I would probably prefer putting everything in the docstrings explicitly, but I'm also happy to use your style (and then without using the `sphinx_autodoc_typehints` extension).  What do you think?

**Comment by ziatdinovmax** [comment]
> By the way, should I be worried about all the warnings that are thrown during `make html`?

Yes :) They usually mean that it has some trouble reading from the docstrings. On the positive side, those messages do make sense in most cases.

**Comment by ziatdinovmax** [comment]
> Sure no problem, I didn't realize it was a standard convention. Would you like me to revert those changes for consistency?

Yes, lets use torch.tensor as tt.

If you could address this and the issue with documentation pages, I will happy to accept this pull request.

**Comment by x94carbone** [comment]
By the way, it looks like these warnings were present in `main` as well:

```
(sphinx) > $ make html                                                                                      [±main ✓]
Running Sphinx v3.0.0
WARNING: html_static_path entry '_static' does not exist
loading pickled environment... done
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 0 source files that are out of date
updating environment: 0 added, 2 changed, 0 removed
reading sources... [100%] utils
WARNING: error while formatting arguments for pyroved.utils.init_dataloader: 'function' object has no attribute '__mro__'
WARNING: error while formatting arguments for pyroved.utils.init_ssvae_dataloaders: 'function' object has no attribute '__mro__'
WARNING: error while formatting arguments for pyroved.utils.generate_grid: 'function' object has no attribute '__mro__'
WARNING: error while formatting arguments for pyroved.utils.generate_latent_grid: 'function' object has no attribute '__mro__'
WARNING: error while formatting arguments for pyroved.utils.transform_coordinates: 'function' object has no attribute '__mro__'
WARNING: error while formatting arguments for pyroved.utils.plot_img_grid: 'function' object has no attribute '__mro__'
WARNING: error while formatting arguments for pyroved.utils.plot_spect_grid: 'function' object has no attribute '__mro__'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] utils
generating indices...  genindexdone
highlighting module code... [100%] pyroved.utils.viz
writing additional pages...  searchdone
copying static files... ... done
copying extra files... done
dumping search index in English (code: en)... done
dumping object inventory... done
build succeeded, 8 warnings.

The HTML pages are in build/html.
```

**Comment by ziatdinovmax** [comment]
> By the way, it looks like these warnings were present in `main` as well:

Hmm... interesting. Let me check it.

**Comment by ziatdinovmax** [comment]
Going forward, we should probably separate PRs addressing documentation from those dealing with changes in the code...

**Comment by x94carbone** [comment]
> Going forward, we should probably separate PRs addressing documentation from those dealing with changes in the code...

Agreed!

**Pull request merged**
